version: 2

aliases:
  - &nix_setup
    run:
      name: Installing the 3rd parties ...
      command: |
        nix-env -i git findutils gnugrep coreutils openssh
        # Circle CI needs git/ssh in /usr/bin
        ln -s $(find /nix -type f -name git | grep libexec | head -n1) /usr/bin
        ln -s $(find /nix -type f -name ssh | grep openssh | head -n1) /usr/bin
jobs:
   build:
     docker:
       - image: nixos/nix
     steps:
       - *nix_setup
       - checkout
       - run: echo "A first hello"
