version: 2

aliases:
  - &local_setup
    run:
      name: Installing the 3rd parties ...
      command: |
        nix-env -i git findutils gnugrep coreutils openssh stack
        # Circle CI needs git/ssh in /usr/bin
        ln -s $(find /nix -type f -name git | grep libexec | head -n1) /usr/bin
        ln -s $(find /nix -type f -name ssh | grep openssh | head -n1) /usr/bin

  - &stack_build
    run:
      name: Building with haskell-stack ...
      command: .ci/build_withStack.sh

  - &build_with_stack
    docker:
      - image: nixos/nix
    steps:
      - checkout
      - *stack_build

jobs:
   build:
     docker:
       - image: nixos/nix
     steps:
       - *local_setup
       - checkout
       - run: echo "A first hello"
       - run: chmod +x .ci/build_withStack.sh
       - run: sh ./.ci/build_withStack.sh
       - run: pwd
       - run: ls -la
       - run: ls -la ./.ci
#       - run: cabal new-build
#       - run: stack build
